#pragma once
#include "afxwin.h"
#include "MyTabBaseDlg.h"

// DChrm_Dlg 对话框

class DChrm_Dlg : public CMyTabBaseDlg
{
	DECLARE_DYNAMIC(DChrm_Dlg)

public:
	DChrm_Dlg(CWnd* pParent = NULL);   // 标准构造函数
	virtual ~DChrm_Dlg();

// 对话框数据
	enum { IDD = IDD_DChrm_Dlg };

protected:
	virtual void DoDataExchange(CDataExchange* pDX);    // DDX/DDV 支持

	DECLARE_MESSAGE_MAP()
public:
	virtual BOOL OnInitDialog();
	CString UpdataCMD(CString sChildstr,int iPos,CString sParestr);
	BOOL UpdataPage(CString sStr);
	void GetCMD();
	afx_msg void OnBnClickedCheckLth();
	void GetAMValue();
	void GetRMValue();
	void GetEMValue();
	void GetHMValue();
	void GetIMValue();
	void GetCMValue();
	void GetDMValue();
	CButton m_Check_Lth;
	CButton m_Check_DT;
	CButton m_Check_PV;
	CButton m_Check_FV;
	CButton m_Check_DN;
	CButton m_Check_ST;
	CButton m_Check_CN;
	CButton m_Check_Res;
	afx_msg void OnBnClickedCheckDt();
	afx_msg void OnBnClickedCheckPv();
	afx_msg void OnBnClickedCheckFv();
	afx_msg void OnBnClickedCheckDn();
	afx_msg void OnBnClickedCheckst();
	afx_msg void OnBnClickedCheckCn();
	afx_msg void OnBnClickedCheckRes();
	afx_msg void OnBnClickedCheckLth2();
	CButton m_Check_Lth2;
	CButton m_Check_DT2;
	CButton m_Check_PV2;
	CButton m_Check_FV2;
	CButton m_Check_DN2;
	CButton m_Check_CN2;
	CButton m_Check_UID;
	CButton m_Check_ST2;
	afx_msg void OnBnClickedCheckDt2();
	afx_msg void OnBnClickedCheckPv2();
	afx_msg void OnBnClickedCheckFv2();
	afx_msg void OnBnClickedCheckDn2();
	afx_msg void OnBnClickedCheckSt2();
	afx_msg void OnBnClickedCheckCn2();
	afx_msg void OnBnClickedCheckUid();
	afx_msg void OnBnClickedCheckSed3();
	CButton m_Check_Sed3;
	CButton m_Check_Azi3;
	CButton m_Check_Alt3;
	CButton m_Check_ND3;
	CButton m_Check_ST3;
	CButton m_Check_CN3;
	CButton m_Check_DN3;
	CButton m_Check_PV3;
	CButton m_Check_FV3;
	CButton m_Check_BL3;
	CButton m_Check_EPSV3;
	CButton m_Check_IM3;
	CButton m_Check_Res31;
	CButton m_Check_Res32;
	CButton m_Check_Res33;
	CButton m_Check_DIS3;
	CButton m_Check_MS3;
	CButton m_Check_GSI3;
	CButton m_Check_CM3;
	CButton m_Check_TM3;
	CButton m_Check_CHMC3;
	CButton m_Check_THMC3;
	CButton m_Check_Res34;
	CButton m_Check_Res35;
	CButton m_Check_Res36;
	CButton m_Check_Res37;
	CButton m_Check_Res38;
	CButton m_Check_Res39;
	CButton m_Check_Res3a;
	CButton m_Check_Res3b;
	CButton m_Check_CA3;
	afx_msg void OnBnClickedCheckCa3();
	CButton m_Check_Lth3;
	CButton m_Check_DT3;
	afx_msg void OnBnClickedCheckAzi3();
	afx_msg void OnBnClickedCheckAlt3();
	afx_msg void OnBnClickedCheckNd3();
	afx_msg void OnBnClickedCheckSt3();
	afx_msg void OnBnClickedCheckCn3();
	afx_msg void OnBnClickedCheckDn3();
	afx_msg void OnBnClickedCheckLth3();
	afx_msg void OnBnClickedCheckDt3();
	afx_msg void OnBnClickedCheckPv3();
	afx_msg void OnBnClickedCheckFv3();
	afx_msg void OnBnClickedCheckBl3();
	afx_msg void OnBnClickedCheckEpsv3();
	afx_msg void OnBnClickedCheckIm3();
	afx_msg void OnBnClickedCheckRes31();
	afx_msg void OnBnClickedCheckRes32();
	afx_msg void OnBnClickedCheckRes33();
	afx_msg void OnBnClickedCheckDis3();
	afx_msg void OnBnClickedCheckMs3();
	afx_msg void OnBnClickedCheckGsi3();
	afx_msg void OnBnClickedCheckCm3();
	afx_msg void OnBnClickedCheckTm3();
	afx_msg void OnBnClickedCheckChmc3();
	afx_msg void OnBnClickedCheckThmc3();
	afx_msg void OnBnClickedCheckRes34();
	afx_msg void OnBnClickedCheckRes35();
	afx_msg void OnBnClickedCheckRes36();
	afx_msg void OnBnClickedCheckRes37();
	afx_msg void OnBnClickedCheckRes38();
	afx_msg void OnBnClickedCheckRes39();
	afx_msg void OnBnClickedCheckRes3a();
	afx_msg void OnBnClickedCheckRes3b();
	afx_msg void OnBnClickedCheckSed4();
	CButton m_Check_Sed4;
	CButton m_Check_Azi4;
	CButton m_Check_Alt4;
	CButton m_Check_ND4;
	CButton m_Check_ST4;
	CButton m_Check_CN4;
	CButton m_Check_DN4;
	CButton m_Check_Lth4;
	CButton m_Check_DT4;
	CButton m_Check_PV4;
	CButton m_Check_FV4;
	CButton m_Check_BL4;
	CButton m_Check_EPSV4;
	CButton m_Check_IM4;
	CButton m_Check_Res41;
	CButton m_Check_Res42;
	CButton m_Check_Res43;
	CButton m_Check_DIS4;
	CButton m_Check_MS4;
	CButton m_Check_GSI4;
	CButton m_Check_CM4;
	CButton m_Check_TM4;
	CButton m_Check_CHMC4;
	CButton m_Check_THMC4;
	CButton m_Check_Res44;
	CButton m_Check_Res45;
	CButton m_Check_Res46;
	CButton m_Check_Res47;
	CButton m_Check_Res48;
	CButton m_Check_Res49;
	CButton m_Check_Res4a;
	CButton m_Check_Res4b;
	afx_msg void OnBnClickedCheckAzi4();
	afx_msg void OnBnClickedCheckAlt4();
	afx_msg void OnBnClickedCheckNd4();
	afx_msg void OnBnClickedCheckSt4();
	afx_msg void OnBnClickedCheckCn4();
	afx_msg void OnBnClickedCheckDn4();
	afx_msg void OnBnClickedCheckLth4();
	afx_msg void OnBnClickedCheckDt4();
	afx_msg void OnBnClickedCheckPv4();
	afx_msg void OnBnClickedCheckFv4();
	afx_msg void OnBnClickedCheckBl4();
	afx_msg void OnBnClickedCheckEpsv4();
	afx_msg void OnBnClickedCheckIm4();
	afx_msg void OnBnClickedCheckRes41();
	afx_msg void OnBnClickedCheckRes42();
	afx_msg void OnBnClickedCheckRes43();
	afx_msg void OnBnClickedCheckDis4();
	afx_msg void OnBnClickedCheckMs4();
	afx_msg void OnBnClickedCheckGsi4();
	afx_msg void OnBnClickedCheckCm4();
	afx_msg void OnBnClickedCheckTm4();
	afx_msg void OnBnClickedCheckChmc4();
	afx_msg void OnBnClickedCheckThmc4();
	afx_msg void OnBnClickedCheckRes44();
	afx_msg void OnBnClickedCheckRes45();
	afx_msg void OnBnClickedCheckRes46();
	afx_msg void OnBnClickedCheckRes47();
	afx_msg void OnBnClickedCheckRes48();
	afx_msg void OnBnClickedCheckRes49();
	afx_msg void OnBnClickedCheckRes4a();
	afx_msg void OnBnClickedCheckRes4b();
	afx_msg void OnBnClickedCheckCa4();
	CButton m_Check_CA4;
	afx_msg void OnBnClickedCheckLth5();
	CButton m_Check_Lth5;
	CButton m_Check_DN5;
	CButton m_Check_DT5;
	CButton m_Check_PV5;
	CButton m_Check_FV5;
	CButton m_Check_ST5;
	CButton m_Check_CN5;
	CButton m_Check_EIM5;
	CButton m_Check_VER5;
	CButton m_Check_IOS5;
	CButton m_Check_GPS5;
	CButton m_Check_BAT5;
	CButton m_Check_CID5;
	CButton m_Check_CSQ5;
	CButton m_Check_TMZ5;
	CButton m_Check_Res5;
	CButton m_Check_CA5;
	afx_msg void OnBnClickedCheckDn5();
	afx_msg void OnBnClickedCheckDt5();
	afx_msg void OnBnClickedCheckPv5();
	afx_msg void OnBnClickedCheckFv5();
	afx_msg void OnBnClickedCheckSt5();
	afx_msg void OnBnClickedCheckCn5();
	afx_msg void OnBnClickedCheckEim5();
	afx_msg void OnBnClickedCheckVer5();
	afx_msg void OnBnClickedCheckIos5();
	afx_msg void OnBnClickedCheckGps5();
	afx_msg void OnBnClickedCheckBat5();
	afx_msg void OnBnClickedCheckCid5();
	afx_msg void OnBnClickedCheckCsq5();
	afx_msg void OnBnClickedCheckTmz5();
	afx_msg void OnBnClickedCheckRes5();
	afx_msg void OnBnClickedCheckCa5();
	afx_msg void OnBnClickedCheckLth6();
	CButton m_Check_Lth6;
	CButton m_Check_DN6;
	CButton m_Check_DT6;
	CButton m_Check_PV6;
	CButton m_Check_FV6;
	CButton m_Check_CN6;
	CButton m_Check_Res61;
	CButton m_Check_Res62;
	CButton m_Check_Res63;
	CButton m_Check_Res64;
	CButton m_Check_Res65;
	CButton m_Check_Res66;
	CButton m_Check_Res67;
	CButton m_Check_Res68;
	CButton m_Check_Res69;
	CButton m_Check_CA6;
	CButton m_Check_ST6;
	afx_msg void OnBnClickedCheckDn6();
	afx_msg void OnBnClickedCheckDt6();
	afx_msg void OnBnClickedCheckPv6();
	afx_msg void OnBnClickedCheckFv6();
	afx_msg void OnBnClickedCheckSt6();
	afx_msg void OnBnClickedCheckCn6();
	afx_msg void OnBnClickedCheckRes62();
	afx_msg void OnBnClickedCheckRes61();
	afx_msg void OnBnClickedCheckRes63();
	afx_msg void OnBnClickedCheckRes64();
	afx_msg void OnBnClickedCheckRes65();
	afx_msg void OnBnClickedCheckRes66();
	afx_msg void OnBnClickedCheckRes67();
	afx_msg void OnBnClickedCheckRes68();
	afx_msg void OnBnClickedCheckRes69();
	afx_msg void OnBnClickedCheckCa6();
	afx_msg void OnBnClickedCheckLth7();
	CButton m_Check_Lth7;
	CButton m_Check_DT7;
	CButton m_Check_PV7;
	CButton m_Check_FV7;
	CButton m_Check_DN7;
	CButton m_Check_ST7;
	CButton m_Check_CN7;
	CButton m_Check_CA7;
	afx_msg void OnBnClickedCheckDt7();
	afx_msg void OnBnClickedCheckPv7();
	afx_msg void OnBnClickedCheckFv7();
	afx_msg void OnBnClickedCheckDn7();
	afx_msg void OnBnClickedCheckSt7();
	afx_msg void OnBnClickedCheckCn7();
	afx_msg void OnBnClickedCheckCa7();
};
